## Dockerfile
# //TODO - don't copy Dockerfile
# FROM minesweeper:latest

FROM node:8.12.0
#FROM mhart/alpine-node:8.12.0

# install bash (needed by some developer tooling)
# RUN apk update 
# RUN apk upgrade 
# RUN apk add bash

# Configure the app
ARG APP_NAME=minesweeper
EXPOSE 8081
ENV PORT 8081

# Set up the application directory
RUN mkdir -p /home/${APP_NAME}
COPY . /home/${APP_NAME}

# Install and run the server
WORKDIR /home/${APP_NAME}
RUN npm install
RUN ls /home/${APP_NAME}

# //TODO - use npm start instead
#CMD node server.js


## Dockerfile-dev
# //TODO - generate this file dynamically

ARG GIT_URL=https://github.com/eclipse/orion.client.git
ENV SHELL /bin/bash
ENV HELM_HOME /home/orion/.helm

WORKDIR /opt/orion

# Dev Environment Setup
RUN sed -i.bak "/^# deb .*partner/ s/^# //" /etc/apt/sources.list \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y curl git apt-transport-https apt-utils build-essential python vim bash-completion sudo libssl-dev libcurl3 \
    && printf "deb https://deb.nodesource.com/node_6.x xenial main\ndeb-src https://deb.nodesource.com/node_6.x xenial main" > /etc/apt/sources.list.d/nodesource.list \
    && curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - \
    && apt-get update \
    && apt-get -y dist-upgrade \
    && curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl \
    && chmod 755 ./kubectl \
    && mv ./kubectl /usr/local/bin/kubectl \
    && curl -L https://clis.ng.bluemix.net/download/bluemix-cli/latest/linux64 | tar vxz \
    && Bluemix_CLI/install_bluemix_cli \
    && rm -rf /var/lib/apt/lists/

RUN useradd --user-group -G sudo --shell /bin/bash --comment "Orion account" --create-home --home-dir /home/orion orion \
    && echo "orion ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/orion \
    && chmod 440 /etc/sudoers.d/orion \
    && runuser -l orion -c "bx plugin install container-service -r Bluemix -f" \
    && runuser -l orion -c "bx plugin install container-registry -r Bluemix -f" \
    && runuser -l orion -c "bx plugin install dev -r Bluemix -f"

# Drop git to this commit (work around bug): e63c9bf4b172a687ffd42ad54fc81ef3a804277a
RUN cd /root && \
    git clone $GIT_URL && \
    cd /root/orion.client/modules/orionode && \
    git checkout e63c9bf4b172a687ffd42ad54fc81ef3a804277a && \
    rm -fr ./node_modules && \
    npm install http-proxy node-pty xterm@2.9.0 && \
    npm install --no-optional && \
    sed -i '/"\/plugins":{/a \                "plugins/consolePlugin.html": true,' ../../bundles/org.eclipse.orion.client.ui/web/defaults.pref && \
    ./node_modules/.bin/grunt --skipTest --fp && \
    rm -fr ./node_modules ./target && \
    npm install http-proxy node-pty xterm@2.9.0 --production && \
    npm install --production --no-optional &&  \
    cd .. && \
    cp -a orionode/. /opt/orion && \
    chown -R orion:orion /opt/orion

RUN curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash

COPY startup.sh /opt/orion/startup.sh
RUN chown root:orion /opt/orion/startup.sh
RUN chmod 550 /opt/orion/startup.sh

#USER orion
VOLUME /home/orion
ENTRYPOINT /opt/orion/startup.sh

#user: orion
#password: 
#kubectl get secret $(kubectl get serviceaccount -o jsonpath="{.items[0].secrets[0].name}") -o jsonpath="{.data.token}" | base64 --decode


